import React, { useState } from "react";
import Header from "./components/Header";
import CreateArea from "./components/CreateArea";
import Footer from "./components/Footer";
import Note from "./components/note";

function App() {

  const [notes, setNotes] = useState([]); //notes has default value of an array

  // Adds a new note to the notes array
  function addNote(newNote) {
    setNotes(prevNotes => {
      // [...prevNotes, newNote] creates a new array
      return [
        ...prevNotes,   // copy all existing notes
        newNote         // add the new note at the end
      ];
    });
  }

  function deleteNote(id) {
    setNotes(prevNotes => {
      return prevNotes.filter((noteItem, index)=>{
        return index !== id;
      });
    });
  }

  return (
    <div>
      <Header />
      <CreateArea
      // passing function as prop
      onAdd= {addNote} 
      />
      {/* index is auto-generated by map. */}
      {notes.map((noteItem, index)=>{
        return <Note
        key= {index} // key helps React optimize rendering
        id={index} // passing index to identify note for deletion
        title= {noteItem.title}
        content = {noteItem.content}
        onDelete= {deleteNote}
        />
      })}
      <Footer />
    </div>
  );
}

export default App;
